esphome:
  name: dts6012m-node
  on_boot:
    priority: -100
    then:
      - if:
          condition:
            lambda: return id(prevent_deep_sleep);
          then:
            - deep_sleep.prevent: deep_sleep_control

esp32:
  board: denky32
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
- platform: esphome
  password: !secret ota_password

wifi:
  use_address: !secret ip_address
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LiDAR_Fallback"
    password: !secret wifi_fallback_outside
    # ap_timeout: 1min

i2c:
  sda: 21
  scl: 18
  scan: false
  # optional: lower clock if unstable
  frequency: 10kHz

captive_portal:

globals:
  - id: prevent_deep_sleep
    type: bool
    restore_value: yes
    initial_value: 'false'

deep_sleep:
  id: deep_sleep_control
  run_duration: 30s
  sleep_duration: 30s

external_components:
  # - source: github://ronmarti/dts6012m-i2c-esphome@v0.1.1
    # components: [dts6012m]
  - source: ./custom_components/dts6012m

dts6012m:
  update_interval: 5000ms
  retries: 3
  distance:
    name: "DTS6012M Distance"

switch:
  - platform: template
    name: "Prevent Deep Sleep"
    id: prevent_deep_sleep_switch
    entity_category: config
    optimistic: true
    lambda: return id(prevent_deep_sleep);
    turn_on_action:
      - globals.set:
          id: prevent_deep_sleep
          value: 'true'
      - deep_sleep.prevent: deep_sleep_control
    turn_off_action:
      - globals.set:
          id: prevent_deep_sleep
          value: 'false'
      - deep_sleep.allow: deep_sleep_control

sensor: